name: Flutter CI

on:
  push:
    branches:
      - main   # Run when you push to main
  pull_request:
    branches:
      - main   # Run on PRs to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0" # or your Flutter version

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run analyzer (optional)
      - name: Analyze project
        run: flutter analyze

      # Run tests (optional)
      - name: Run tests
        run: flutter test

      # Build APK
      - name: Build APK
        run: flutter build apk --release

      # Save APK as GitHub artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
