name: Flutter CI

on:
  push:
    branches:
      - main   # Run when you push to main
  pull_request:
    branches:
      - main   # Run on PRs to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # safer with Flutter 3.22+

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0" # match your local version

      - name: Install Android SDK tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip wget
          sdkmanager --version || true

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses || true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
